### ISSUE TITLE
add react eslint rules

### ISSUE THREAD

**Issue by jimmy-guzman** [jimmy-guzman/eslint-config-jimmy-guzman#4]
### Describe the feature you'd like:
* add [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react) rules
* add [eslint-plugin-react-hooks](https://github.com/facebook/react/tree/main/packages/eslint-plugin-react-hooks) rules
* add [eslint-plugin-jsx-a11y](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y) rules
 
### Suggested implementation:
- [ ] wait for [eslint-plugin-jsx-a11y ESLint 8.x support](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/809)
- [ ] wait for [eslint-plugin-react-hooks ESLint 8.x support](https://github.com/facebook/react/issues/22533)
- [ ] wait for [eslint-plugin-react support](https://github.com/yannickcr/eslint-plugin-react/issues/3055)
